// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package drivers

import (
	"context"
	"firestore_clean/adapters/controllers"
	"firestore_clean/adapters/gateways"
	"firestore_clean/adapters/presenters"
	"firestore_clean/drivers/database"
	"firestore_clean/usecases/interactors"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func InitializeUserDriver(ctx context.Context) (User, error) {
	echoEcho := echo.New()
	outputFactory := NewOutputFactory()
	inputFactory := NewInputFactory()
	repositoryFactory := NewRepositoryFactory()
	client, err := database.NewCllient(ctx)
	if err != nil {
		return nil, err
	}
	user := controllers.NewUserController(outputFactory, inputFactory, repositoryFactory, client)
	driversUser := NewUserDriver(echoEcho, user)
	return driversUser, nil
}

// wire.go:

func NewOutputFactory() controllers.OutputFactory {
	return presenters.NewUserOutputPort
}

func NewInputFactory() controllers.InputFactory {
	return interactors.NewUserInputPort
}

func NewRepositoryFactory() controllers.RepositoryFactory {
	return gateways.NewUserRepository
}
